### PR TITLE
npm init, installed jest, configured jest, created example unit test

### PR DESCRIPTION
**Pull request by christofferaakre**
With this pull request, `jest` has been setup and configured, and there is an example unit test in `tests/Vector/Vector.test.js` that shows how to write unit tests in this codebase. It's pretty hacky, but I think it's the best we can do. You'll see I explained in 
the comment in the `tests/Vector/Vector.test.js` file how we need to use `require` to run the code in the script containing the functions we want to test in order for those functions to be defined, as we can not use modules in the browser without a http server unfortunately. I will take a look into creating a script or something of the sort that will automatically require everything necessary, so that even if we are testing a function that is defined in a script that depends on multiple other scripts having been run before it, it will be just a one-liner to do require all of them. Currently, you would need to `require` each script that the main script depends on individually.

### CODE REVIEW

**Comment by christofferaakre** [comment]
Actually, it is not this simple. In the example I gave above it just so happened to work since the only code in `Physics.js` is 
`var Physics ={};`, and I just hardcoded in `Physics = {};` as a global variable. If you try to instead do `require('../../namespaces/Physics.js` you will in fact get an error because `Physics` will not be defined since we are not using global variables (nor should we). Here is a script I wrote to try to automatically require everything:
```javascript
// require-everything.js
const shell = require('shelljs');
const path = require('path');

// This shell script prints all the scripts referenced in the index.html file, so we capture
// its output here
const scripts = shell.exec("./import", {async: false}).stdout.split('\n');

scripts.forEach(script => {
  // Ignoring empty string at the end
  if (script) {
    const path_to_script = path.join(__dirname, script);
    require(path_to_script);
  }
})
```
and the accompanying shell script:
```bash
# ./import
#!/usr/bin/env bash

# This script gets the filenames of all the scripts
# referenced in index.html, ignoring scripts that have
# been commented out, then prints that to standard output

# setting IFS makes sure that bash doesn't remove
# newlines when we save the output of cat to a variable
IFS=
SCRIPTS="$(cat "index.html" | grep .js | grep --invert-match "<!" | awk -F'"' '{print $2}')"
echo $SCRIPTS
```

The output of the shell script is: 
```console
negosaki@negosaki:~/qmul/project/WeLD$ ./import
modules/helpers.js
namespaces/Physics.js
namespaces/Graphics.js
modules/physics/Lattice.js
modules/physics/Harmonic.js
modules/physics/Verlet.js
modules/physics/Units.js
modules/physics/Vector.js
modules/physics/Temperature.js
modules/physics/ForceMap.js
modules/graphics/UserInterface.js
modules/graphics/Renderer.js
WeLD.js
```
Upon running `require-everything.js`, this happens:
```console
negosaki@negosaki:~/qmul/project/WeLD$ node require-everything.js 
modules/helpers.js
namespaces/Physics.js
namespaces/Graphics.js
modules/physics/Lattice.js
modules/physics/Harmonic.js
modules/physics/Verlet.js
modules/physics/Units.js
modules/physics/Vector.js
modules/physics/Temperature.js
modules/physics/ForceMap.js
modules/graphics/UserInterface.js
modules/graphics/Renderer.js
WeLD.js
/home/negosaki/qmul/project/WeLD/modules/physics/Lattice.js:396
Physics.Lattice = new Lattice();
^

ReferenceError: Physics is not defined
    at Object.<anonymous> (/home/negosaki/qmul/project/WeLD/modules/physics/Lattice.js:396:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /home/negosaki/qmul/project/WeLD/require-everything.js:12:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/negosaki/qmul/project/WeLD/require-everything.js:8:9)
```
The first output is from the `echo` in the shell script since the js script runs the shell script, but then we se `Physics is not defined`, because the variables are not global. So unfortunately, I do not really see a way to implement proper unit testing here. Maybe someone else has any ideas on how to achieve this?

**Comment by aephil** [comment]
Hmmm, is the hacky first approach (i.e., the one committed, not the one involving the shell script) good enough for now? I am most concerned about testing small units so we don't necessarily need the full infrastructure available to the tests.

That is, do you have a use case where you want to `require` everything at once?

**Comment by christofferaakre** [comment]
@aephil I don't think it is. The only reason the example I gave worked was because the `namespaces/Physics.js` file contains only the line `var Physics = {}`. For scripts that depend on scripts with more substantial code in them, it won't work.

**Comment by aephil** [comment]
@christofferaakre I understand the problem, I'm just not sure what we want to test (for now) that falls foul of it. It seems to me that, especially for this very fundamental code, testing a single script is all we need to do. Certainly your example is enough to test the valence angles along the lines of my script in #19.

On the other hand, I don't think it would in fact be so difficult to refactor the code so that it doesn't rely on running those scripts in that order (i.e., each script imports the bits it specifically needs). Re your comment about requiring an http server, I run for testing purposes using the built-in one from python, `python -m http.server`, which works fine, and there is also one on `npm` since I see you are using Node. Would using one of these allow you to refactor in this way?

Let's discuss further at our meeting tomorrow.

**Comment by christofferaakre** [comment]
@aephil Okay, yeah fair enough. The functions defined in `modules/physics/Forcemap.js` are indeed self-sufficient, so we can use the same trick of using a global variable to set `Physics = {}` and it works. See this commit https://github.com/aephil/WeLD/commit/fe62f865e01ecffbf6f753c93c63695f6579eebf#
By the way, you can run the tests with `npm test`.

 If we set up some mock fixture data to pass to the functions, it should be doable. I will go ahead and do this. And yeah, I was experimenting with using `http.server` as well as `live-server` from node. Rewriting seems to still be a real pain, but we could potentially rewrite only the parts of the codebase that are not entangled with other scripts, such as `modules/physics/Forcemap.js`.
I will have a go at this as well.

**Comment by christofferaakre** [comment]
@aephil I re-adapted your test as a unit test; see `tests/forces/valenceAngle.test.js` per my commit https://github.com/aephil/WeLD/commit/9683efe86f0a6a7640674bea0deec2118e8c0c0e. If you try running `npm test`, you get the following error message:
sub
 This happens because the `valenceAngle` function depends on `Physics.Vector`, which is assigned to the empty 
`Physics.js` namespace earlier in the code. So we would need to also `require ../../modules/physics/Vector`, which I have done in the next commit https://github.com/aephil/WeLD/commit/01b2a2f0c614a978833b062c2a51d79d6684bb29, and with that, the test passes:
passing

So, it kind of works, but it is not very convenient having to do a treasure hunt making sure that we are requiring every script that our main script depends on.

**Comment by christofferaakre** [comment]
@aephil I did some testing on a new `modules` branch, and there is an issue where the browser expects ES6 modules with `<script type="module">`, e.g. `export default new ForceMap()` in `modules/physics/ForceMap.js` like `import ForceMap from './modules/physics/ForceMap.js` in `WeLD.js`, but then for our unit tests, nodejs expects nodejs modules, e.g. `modules.export = {new ForceMap(), initValence}` in `modules/physics/ForceMap.js` and `const ForceMap = require('../../modules/physics/ForceMap')` in `tests/forces/testForce.test.js`, and the two clash. We can get the unit tests to work if we use NodeJS modules, or we can get the `WeLD.js` script to work by using ES6 modules, but in both cases, the other breaks, even if we don't do any imports or `require`s in the respective file. And even if we could get both working at the same time, we would still need to `require` every script that the main script we wish to test depends on. So it seems like using a web server and http modules doesn't really help much after all unless we rewrote the entire codebase such that scripts don't depend on each other and simply use imports/exports, but I had a go at doing that when I was trying to rewrite the code in TypeScript and it was really complicated, especially consdering the way namespaces are being set up currently, with `namespaces/Physics.js` for example containing the sole line `var physics = {};`, and then other scripts are run later simply modify the `Physics` object.

I think for now we will just have to deal with having to `require` the script we want to test, and when we get error messages saying stuff is not defined, we will have to hunt down the things that are not defined, determine which script defines that thing and then require that script as well in our test file. Again, this is really hacky, but I don't see another way to do it.

**Comment by christofferaakre** [comment]
During the project meeting, we determined that if we want to use modules both in nodejs and in the browser, we probably need to use something like Rollup or Webpack (much more bloated) to transpile our code. However, this alone will not let us test functions without potentially needing to do many `requires` and potentially it flat out not being possible to test certain lines of code. For that, we would need to rewrite the entire codebase such that scripts do not rely on other scripts having been executed before them, but inside import and export functions, variables, etc. as necessary.

**Pull request merged**
