### PR TITLE
add experimental features and cleanup ui

### PR DESCRIPTION
**Pull request by TakudzwaMakoni**
Adding experimental features that may be helpful. May be updating/cleaning up files relating to UI now that we are using npm

### CODE REVIEW

**Comment by christofferaakre** [comment]
Just looked at this now, and this looks really nice! Great job. You can merge this in whenever you like.

**Review by christofferaakre — APPROVED** [review]
Looks good to me

**Comment by TakudzwaMakoni** [comment]
i need you to check if my changes arent breaking anything you are working on. Its a lot of changes but the most important change is the structure of how various data is shared among Renderer, UserInterface, and Lattice. 

I felt that constantly passing in lattice into ui or or renderer was messy, even if they are used references. Since i have refactored them to classes, they can inherit shared data and conveniently operate on that shared data independently without having to pass a lattice object into the ui if you only really want e.g. the nodes of the lattice.

The classes Renderer, UserInterface, Terminal, and Lattice are children to the parent class Data. By extending this parent class, they can share between them some common object. 

Any of these classes can access shared data by `this.shareData` which is an object that contains common data like the array of the lattice nodes, the quantities of the lattice, which node has been selected (highlighted) by user input etc.

I know there has been a back and forth about the naming of the lattice 'data', meaning where the nodes are actually stored. You will appreciate that as the code becomes more complex, e.g adding other lattice metadata like its size name, KE / PE, using 'data' to refer to the actual nodes becomes ambiguous, so i reverted to nodes. For example:

- to access the array of nodes within any of the classes mentioned, you would use `this.sharedData.nodes`.
- to access the quantities of the lattice, you would use `this.sharedData.qauntities`, this lives is created by Lattice, but lives in sharedData since UserInterface or Renderer may also want to use this data.
-  Another example is `this.sharedData.highlighted` which both Renderer and UserInterFace want to use, whose value we want to make sure they are in agreement with each other when the simulation is running. 

Instead of passing the lattice to your force functions i have passed 'this.sharedData' using 'shared' as an argument variable, because I noticed that you sometimes need other lattice data beside the nodes, such as the quantities. Since nodes and quantities both live in sharedData, you still are able to use access the data you need by using `shared.nodes` or `shared.quantities`.

Hopefully I am making sense. Have a look to see if my changes break anything you are doing, its a big refactor. I have got both your testScripts running again, so i only think i have considered everything.

**Comment by christofferaakre** [comment]
> i need you to check if my changes arent breaking anything you are working on. Its a lot of changes but the most important change is the structure of how various data is shared among Renderer, UserInterface, and Lattice.
> 
> I felt that constantly passing in lattice into ui or or renderer was messy, even if they are using them as references. Since i have refactored them to classes, they can inherit shared data and conveniently operate on that shared data independently without having to pass the whole lattice object into the ui if you only really want e.g. the nodes of the lattice.
> 
> The classes Renderer, UserInterface, Terminal, and Lattice are children to the parent class Data. By extending this parent class, they can share between them some common object.
> 
> Any of these classes can access shared data by `this.sharedData` which is an object that contains common data like the array of the lattice nodes, the quantities of the lattice, which node has been selected (highlighted) by user input etc.
> 
> I know there has been a back and forth about the naming of the lattice 'data', meaning where the nodes are actually stored. You will appreciate that as the code becomes more complex, e.g adding other lattice metadata like its size name, KE / PE, using 'data' to refer to the actual nodes becomes ambiguous, so i reverted to nodes. For example:
> 
> * to access the array of nodes within any of the classes mentioned, you would use `this.sharedData.nodes`.
> * to access the quantities of the lattice, you would use `this.sharedData.qauntities`, this is created by Lattice, but lives in sharedData since UserInterface or Renderer may also want to use this data.
> * Another example is `this.sharedData.highlighted` which both Renderer and UserInterFace want to use, whose value we want to make sure they are in agreement with each other when the simulation is running.
> 
> Instead of passing the lattice to your force functions i have passed 'this.sharedData' using 'shared' as an argument variable, because I noticed that you sometimes need other lattice data beside the nodes, such as the quantities. Since nodes and quantities both live in sharedData, you still are able to use access the data you need by using `shared.nodes` or `shared.quantities`.
> 
> Hopefully I am making sense. Have a look to see if my changes break anything you are doing, its a big refactor. I have got both your testScripts running again, so i only think i have considered everything.
> 
> @christofferaakre

I was actually planning to do a refactor like this, but hadn't got around to this, so we are definitely on the same page. I looked through your changes, and nothing seems to disrupt what I am doing, I also pulled your changes and verified that nothing is broken on my end either. This is really nice, thanks a lot for this!
@TakudzwaMakoni

**Pull request merged**
