### PR TITLE
[Closes issue #32] Sum up all forces and then do one big verlet step

### PR DESCRIPTION
**Pull request by christofferaakre**
[Closes issue #32] Calculate total force and then do one big verlet step

### CODE REVIEW

**Comment by christofferaakre** [comment]
This should fix #32 I believe. Tested with the `simulations/spring/testSpring.js` simulation. It also makes the beheaviour in the `testSpring2.js` seem like it could be correct, so I am pretty sure this fixes it properly. Let me know if I should merge this in @aephil @TakudzwaMakoni

**Comment by christofferaakre** [comment]
If nothing looks wrong, can I get a 'this looks good'? I would prefer not to merge it in before anyone looks at it because it is a decently sized pull request.
@aephil @TakudzwaMakoni

**Comment by TakudzwaMakoni** [comment]
Hi, will have to take a look at it this evening latest

**Comment by christofferaakre** [comment]
@TakudzwaMakoni I am pretty sure it is correct, so since you didn't respond yet, I will just merge it in. Besides, I have a big refactor after this that depends on these changes that I want to merge in, so I need to merge this first.

**Comment by TakudzwaMakoni** [comment]
yes it looks fine. Apologies, i am not as available as i like anymore as i am employed elsewhere now. where are you calculating the future force when you resolve all the forces?

**Comment by TakudzwaMakoni** [comment]
https://github.com/TakudzwaMakoni/xWeLD/blob/main/backend/src/physics/harmonic/spring.rs

Take a look at this. (this is another version of WeLD i wrote as an exercise in rust as i needed to learn it for work)

now my forces return not three, but six force components:

x,y,z,x2,y2,z2.

namely xyz and future xyz.

in the big final verlet step, i then use the future forces as per the vv algorithm of an equivalent form:

`let rf = vec::add(position, vec::scale(DT, v_half));
 let vf = vec::add(velocity, vec::scale(DT * 0.5 * (1./node.mass), vec::add(net_future_force, net_force)));
`

**Comment by christofferaakre** [comment]
@TakudzwaMakoni I really appreciate that you took the time to reply here anyway! In the implementation of 'integrationStep' in 'Verlet.js' I am computing the forces, then doing the first half of the verket algorithm, then computing the forces again (future force), and then doing the second half of the algorithm

**Comment by TakudzwaMakoni** [comment]
this looks to be correct, so the merge looks good to me.

In the immediate next few weeks, i am probably going to be unavailable, save for code reviews which i can perhaps do in the weekends. I may have to limit my code contribution to weekends too going forward

**Comment by christofferaakre** [comment]
@TakudzwaMakoni I completely understand. Honestly, if you are happy with me just pushing major changes and merging my own pull requests without bothering you, I am happy to do so.

**Comment by TakudzwaMakoni** [comment]
its not a bother at all. don't hesitate to reach me if there is anything time sensitive, i'll try to be of assistance as soon as i can

**Pull request merged**
