### PR TITLE
Calculate energies over time

### PR DESCRIPTION
**Pull request by christofferaakre**
Calculate kinetic, potential, and total energy over time, as well as allowing for arbitrary quantities (functions of the lattice) to be calculated over time. 

This has been implemented, but in the case of just a simple 2-particle system with a harmonic spring bond between them, it seems that total energy is not conserved, so something must be going wrong.

### CODE REVIEW

**Comment by christofferaakre** [comment]
This should not be merged until we figure out why the total energy is apparantly not being conserved. My hunch is that the issue lies in how we are calculating the potential energy, as I think the kinetic energy is being calculated correctly, although there could potentially still be issues with our actual simulation itself. However, the system seems stable even in more complicated setups, so I think total energy is being conserved. 
Any comments would be much appreciated.
@TakudzwaMakoni @aephil @Paddy198

**Comment by TakudzwaMakoni** [comment]
will take a look at this and let you know what i think. I will need time to familiarise with changes

**Comment by TakudzwaMakoni** [comment]
since you are'nt calculating the potential energy contributions for the valence angles and lennard jones in ForceMap.js, don't you want to return zero inside their actions? You aren't returning anything, but it looks like Verlet.js expects something back to add to the total potential energy

**Comment by christofferaakre** [comment]
> 

Yes sorry that is correct, I didn't code in the potentials for the other forces as I wanted to just test the spring potential first. If you look at the `simulations/spring/testSpring.js` simulation, that one only uses the spring force/potential and it still doesn't conserve the total energy.

**Comment by TakudzwaMakoni** [comment]
How are you testing the kinetic / potential energy?

**Comment by christofferaakre** [comment]
> How are you testing the kinetic / potential energy?

You can see in `simulations/spring/testSpring.js`, I am calculating the potential and kinetic energy, adding them, and printing that to the console

**Comment by TakudzwaMakoni** [comment]
It looks like you were only sampling quantities every 100 updates to calculate your mean, and calling your debug function in renderer.js before all the updates were complete. I think i have fixed it, as the mean values look right.

**Comment by christofferaakre** [comment]
> It looks like you were only sampling quantities every 100 updates to calculate your mean, and calling your debug function in renderer.js before all the updates were complete. I think i have fixed it, as the mean values look right.

With these changes, you are calculating the mean total energy right? I see that indeed this stays constant. However, shouldn't the total energy itself be constant, not just the 'mean total energy'? If you also log the current total energy, you see that it fluctuates wildly.
@TakudzwaMakoni

**Comment by TakudzwaMakoni** [comment]
yes you are right, TE should also be constant at any given moment. there are typo in my changes too, mean KE is actually constant at ~100 and mean PE constant at ~49. 

Potential of each node is 0.5 * k * x^2 right, the integral of the force, then for a two bonded system is k(r0 - r1)^2, like in your document https://hal-mines-paristech.archives-ouvertes.fr/hal-00924263/document

**Comment by christofferaakre** [comment]
> 

What you just wrote made me realise what the problem is! The document has the potential as kx^2 and the force as -2kx, so thats what I put in `ForceMap.js`. However, the `spring` functions only returns the force on one of the atoms, so it should also only return the potential on one atom, aka half the potential of the entire system since the two atoms both have the same potential. Thus, I now have the force as `-2kx` as before, but the potential as `k/2 x^2`, when I did this the total energy is now conserved!
@TakudzwaMakoni 
I will do some cleanup later today probably and then merge this in.
Thanks so much for the help in figuring this out, and I saw you did a bunch of other cleanup too in the diff, thanks a lot for that too.

**Comment by TakudzwaMakoni** [comment]
I am glad to hear. Is there a reason you are multiplying the PE by the mass also? My latest commit removed this, so if you had a reason to do this you may want to re-add it, I couldn't think of why we do that at the time.

**Comment by christofferaakre** [comment]
> I am glad to hear. Is there a reason you are multiplying the PE by the mass also? My latest commit removed this, so if you had a reason to do this you may want to re-add it, I couldn't think of why we do that at the time.

Yeah on second thought we don't need to multiply by mass, thanks for pointing that out

**Comment by christofferaakre** [comment]
I will merge this in now.

**Pull request merged**
